# MySQL????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/granary?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

